reader:
  app:
    workDir: "."
    showUI: false
    debug: false
    packaged: false
    secure: false
    inviteCode: ""
    secureKey: ""
    debugLog: false
    userLimit: 50
    userBookLimit: 200
    mongoUri: ""
    mongoDbName: "reader"
    cacheChapterContent: true
    remoteActivateUrl: "https://r.htmake.com/reader3/activateLicense"
    remoteActivateEnabled: false
    autoBackupUserData: false
    autoClearInactiveUser: 0
    shelfUpdateInteval: 30
    autoBackupIntervalMs: 3600000
    autoClearIntervalMs: 86400000
    smtpHost: ""
    smtpPort: 465
    smtpUser: ""
    smtpPassword: ""
    smtpFrom: ""
    smtpSsl: true
    smtpStartTls: false
  server:
    port: 8080

server:
  port: 8080

spring:
  main:
    web-application-type: none
  application:
    name: reader-pro

logging:
  level:
    root: INFO
    com.htmake.reader: INFO
