reader:
  app:
    workDir: "."
    showUI: false
    debug: false
    packaged: false
    secure: false
    inviteCode: ""
    secureKey: ""
    debugLog: false
    userLimit: 50
    userBookLimit: 200
    mongoUri: ""
    mongoDbName: "reader"
    cacheChapterContent: true
  server:
    port: 8080

server:
  port: 8080

spring:
  main:
    web-application-type: none
  application:
    name: reader-pro

logging:
  level:
    root: INFO
    com.htmake.reader: INFO
