package me.ag2s.epublib.domain;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.namespace.QName;
import me.ag2s.epublib.util.StringUtil;

public class Metadata implements Serializable {
   private static final long serialVersionUID = -2437262888962149444L;
   public static final String DEFAULT_LANGUAGE = "en";
   private boolean autoGeneratedId;
   private List authors = new ArrayList();
   private List contributors = new ArrayList();
   private List dates = new ArrayList();
   private String language = "en";
   private Map otherProperties = new HashMap();
   private List rights = new ArrayList();
   private List titles = new ArrayList();
   private List identifiers = new ArrayList();
   private List subjects = new ArrayList();
   private String format;
   private List types;
   private List descriptions;
   private List publishers;
   private Map metaAttributes;

   public Metadata() {
      this.format = MediaTypes.EPUB.getName();
      this.types = new ArrayList();
      this.descriptions = new ArrayList();
      this.publishers = new ArrayList();
      this.metaAttributes = new HashMap();
      this.identifiers.add(new Identifier());
      this.autoGeneratedId = true;
   }

   public boolean isAutoGeneratedId() {
      return this.autoGeneratedId;
   }

   public Map getOtherProperties() {
      return this.otherProperties;
   }

   public void setOtherProperties(Map otherProperties) {
      this.otherProperties = otherProperties;
   }

   public Date addDate(Date date) {
      this.dates.add(date);
      return date;
   }

   public List getDates() {
      return this.dates;
   }

   public void setDates(List dates) {
      this.dates = dates;
   }

   public Author addAuthor(Author author) {
      this.authors.add(author);
      return author;
   }

   public List getAuthors() {
      return this.authors;
   }

   public void setAuthors(List authors) {
      this.authors = authors;
   }

   public Author addContributor(Author contributor) {
      this.contributors.add(contributor);
      return contributor;
   }

   public List getContributors() {
      return this.contributors;
   }

   public void setContributors(List contributors) {
      this.contributors = contributors;
   }

   public String getLanguage() {
      return this.language;
   }

   public void setLanguage(String language) {
      this.language = language;
   }

   public List getSubjects() {
      return this.subjects;
   }

   public void setSubjects(List subjects) {
      this.subjects = subjects;
   }

   public void setRights(List rights) {
      this.rights = rights;
   }

   public List getRights() {
      return this.rights;
   }

   public String getFirstTitle() {
      if (this.titles != null && !this.titles.isEmpty()) {
         for(String title : this.titles) {
            if (StringUtil.isNotBlank(title)) {
               return title;
            }
         }

         return "";
      } else {
         return "";
      }
   }

   public String addTitle(String title) {
      this.titles.add(title);
      return title;
   }

   public void setTitles(List titles) {
      this.titles = titles;
   }

   public List getTitles() {
      return this.titles;
   }

   public String addPublisher(String publisher) {
      this.publishers.add(publisher);
      return publisher;
   }

   public void setPublishers(List publishers) {
      this.publishers = publishers;
   }

   public List getPublishers() {
      return this.publishers;
   }

   public String addDescription(String description) {
      this.descriptions.add(description);
      return description;
   }

   public void setDescriptions(List descriptions) {
      this.descriptions = descriptions;
   }

   public List getDescriptions() {
      return this.descriptions;
   }

   public Identifier addIdentifier(Identifier identifier) {
      if (this.autoGeneratedId && !this.identifiers.isEmpty()) {
         this.identifiers.set(0, identifier);
      } else {
         this.identifiers.add(identifier);
      }

      this.autoGeneratedId = false;
      return identifier;
   }

   public void setIdentifiers(List identifiers) {
      this.identifiers = identifiers;
      this.autoGeneratedId = false;
   }

   public List getIdentifiers() {
      return this.identifiers;
   }

   public void setFormat(String format) {
      this.format = format;
   }

   public String getFormat() {
      return this.format;
   }

   public String addType(String type) {
      this.types.add(type);
      return type;
   }

   public List getTypes() {
      return this.types;
   }

   public void setTypes(List types) {
      this.types = types;
   }

   public String getMetaAttribute(String name) {
      return (String)this.metaAttributes.get(name);
   }

   public void setMetaAttributes(Map metaAttributes) {
      this.metaAttributes = metaAttributes;
   }
}
