package com.htmake.reader.lib.tts.model
import com.htmake.reader.lib.tts.constant.*
import com.htmake.reader.lib.tts.util.Tools

class SSML private constructor(private var synthesisText:String?,private var voice:VoiceEnum?,private var rate:String?,private var pitch:String?,private var volume:String?,private var style:TtsStyleEnum?,private var outputFormat:OutputFormat?) {
    fun getSynthesisText()=synthesisText; fun setSynthesisText(value:String?){synthesisText=value}; fun getVoice()=voice; fun setVoice(value:VoiceEnum?){voice=value}; fun getRate()=rate; fun setRate(value:String?){rate=value}; fun getPitch()=pitch; fun setPitch(value:String?){pitch=value}; fun getVolume()=volume; fun setVolume(value:String?){volume=value}; fun getStyle()=style; fun setStyle(value:TtsStyleEnum?){style=value}; fun getOutputFormat()=outputFormat; fun setOutputFormat(value:OutputFormat?){outputFormat=value}
    override fun toString():String { val selected=voice?:VoiceEnum.zh_CN_XiaoxiaoNeural; val opening=style?.let { String.format("<mstts:express-as style='%s'>\r\n",it.getValue()) }?:""; val closing=if(style==null)"" else "</mstts:express-as>"; return String.format(SSML_PATTERN,Tools.getRandomId(),Tools.date(),selected.getLocale(),selected.getShortName(),opening,pitch?:"+0Hz",rate?:"+0%",volume?:"+0%",synthesisText,closing) }
    class SSMLBuilder { private var synthesisText:String?=null; private var voice:VoiceEnum?=null; private var rate:String?=null; private var pitch:String?=null; private var volume:String?=null; private var style:TtsStyleEnum?=null; private var outputFormat:OutputFormat?=null; fun synthesisText(value:String?)=apply{synthesisText=value}; fun voice(value:VoiceEnum?)=apply{voice=value}; fun rate(value:String?)=apply{rate=value}; fun pitch(value:String?)=apply{pitch=value}; fun volume(value:String?)=apply{volume=value}; fun style(value:TtsStyleEnum?)=apply{style=value}; fun outputFormat(value:OutputFormat?)=apply{outputFormat=value}; fun build()=SSML(synthesisText,voice,rate,pitch,volume,style,outputFormat) }
    companion object { @JvmField var SSML_PATTERN="X-RequestId:%s\r\nContent-Type:application/ssml+xml\r\nX-Timestamp:%sZ\r\nPath:ssml\r\n\r\n<speak version='1.0' xmlns='http://www.w3.org/2001/10/synthesis' xmlns:mstts='https://www.w3.org/2001/mstts' xml:lang='%s'>\r\n<voice name='%s'>\r\n%s<prosody pitch='%s' rate='%s' volume='%s'>%s</prosody>%s</voice></speak>"; @JvmStatic fun builder()=SSMLBuilder() }
}
