// 
// Decompiled by Procyon v0.6.0
// 

package me.ag2s.epublib.domain;

import java.util.Iterator;
import me.ag2s.epublib.util.StringUtil;
import java.util.HashMap;
import java.util.ArrayList;
import javax.xml.namespace.QName;
import java.util.Map;
import java.util.List;
import java.io.Serializable;

public class Metadata implements Serializable
{
    private static final long serialVersionUID = -2437262888962149444L;
    public static final String DEFAULT_LANGUAGE = "en";
    private boolean autoGeneratedId;
    private List<Author> authors;
    private List<Author> contributors;
    private List<Date> dates;
    private String language;
    private Map<QName, String> otherProperties;
    private List<String> rights;
    private List<String> titles;
    private List<Identifier> identifiers;
    private List<String> subjects;
    private String format;
    private List<String> types;
    private List<String> descriptions;
    private List<String> publishers;
    private Map<String, String> metaAttributes;
    
    public Metadata() {
        this.authors = new ArrayList<Author>();
        this.contributors = new ArrayList<Author>();
        this.dates = new ArrayList<Date>();
        this.language = "en";
        this.otherProperties = new HashMap<QName, String>();
        this.rights = new ArrayList<String>();
        this.titles = new ArrayList<String>();
        this.identifiers = new ArrayList<Identifier>();
        this.subjects = new ArrayList<String>();
        this.format = MediaTypes.EPUB.getName();
        this.types = new ArrayList<String>();
        this.descriptions = new ArrayList<String>();
        this.publishers = new ArrayList<String>();
        this.metaAttributes = new HashMap<String, String>();
        this.identifiers.add(new Identifier());
        this.autoGeneratedId = true;
    }
    
    public boolean isAutoGeneratedId() {
        return this.autoGeneratedId;
    }
    
    public Map<QName, String> getOtherProperties() {
        return this.otherProperties;
    }
    
    public void setOtherProperties(final Map<QName, String> otherProperties) {
        this.otherProperties = otherProperties;
    }
    
    public Date addDate(final Date date) {
        this.dates.add(date);
        return date;
    }
    
    public List<Date> getDates() {
        return this.dates;
    }
    
    public void setDates(final List<Date> dates) {
        this.dates = dates;
    }
    
    public Author addAuthor(final Author author) {
        this.authors.add(author);
        return author;
    }
    
    public List<Author> getAuthors() {
        return this.authors;
    }
    
    public void setAuthors(final List<Author> authors) {
        this.authors = authors;
    }
    
    public Author addContributor(final Author contributor) {
        this.contributors.add(contributor);
        return contributor;
    }
    
    public List<Author> getContributors() {
        return this.contributors;
    }
    
    public void setContributors(final List<Author> contributors) {
        this.contributors = contributors;
    }
    
    public String getLanguage() {
        return this.language;
    }
    
    public void setLanguage(final String language) {
        this.language = language;
    }
    
    public List<String> getSubjects() {
        return this.subjects;
    }
    
    public void setSubjects(final List<String> subjects) {
        this.subjects = subjects;
    }
    
    public void setRights(final List<String> rights) {
        this.rights = rights;
    }
    
    public List<String> getRights() {
        return this.rights;
    }
    
    public String getFirstTitle() {
        if (this.titles == null || this.titles.isEmpty()) {
            return "";
        }
        for (final String title : this.titles) {
            if (StringUtil.isNotBlank(title)) {
                return title;
            }
        }
        return "";
    }
    
    public String addTitle(final String title) {
        this.titles.add(title);
        return title;
    }
    
    public void setTitles(final List<String> titles) {
        this.titles = titles;
    }
    
    public List<String> getTitles() {
        return this.titles;
    }
    
    public String addPublisher(final String publisher) {
        this.publishers.add(publisher);
        return publisher;
    }
    
    public void setPublishers(final List<String> publishers) {
        this.publishers = publishers;
    }
    
    public List<String> getPublishers() {
        return this.publishers;
    }
    
    public String addDescription(final String description) {
        this.descriptions.add(description);
        return description;
    }
    
    public void setDescriptions(final List<String> descriptions) {
        this.descriptions = descriptions;
    }
    
    public List<String> getDescriptions() {
        return this.descriptions;
    }
    
    public Identifier addIdentifier(final Identifier identifier) {
        if (this.autoGeneratedId && !this.identifiers.isEmpty()) {
            this.identifiers.set(0, identifier);
        }
        else {
            this.identifiers.add(identifier);
        }
        this.autoGeneratedId = false;
        return identifier;
    }
    
    public void setIdentifiers(final List<Identifier> identifiers) {
        this.identifiers = identifiers;
        this.autoGeneratedId = false;
    }
    
    public List<Identifier> getIdentifiers() {
        return this.identifiers;
    }
    
    public void setFormat(final String format) {
        this.format = format;
    }
    
    public String getFormat() {
        return this.format;
    }
    
    public String addType(final String type) {
        this.types.add(type);
        return type;
    }
    
    public List<String> getTypes() {
        return this.types;
    }
    
    public void setTypes(final List<String> types) {
        this.types = types;
    }
    
    public String getMetaAttribute(final String name) {
        return this.metaAttributes.get(name);
    }
    
    public void setMetaAttributes(final Map<String, String> metaAttributes) {
        this.metaAttributes = metaAttributes;
    }
}
