package me.ag2s.epublib.domain

import java.io.Serializable
import me.ag2s.epublib.util.StringUtil

class Metadata : Serializable {
    private var autoGeneratedId = true
    private var authors: MutableList<Author> = ArrayList(); private var contributors: MutableList<Author> = ArrayList(); private var dates: MutableList<Date> = ArrayList(); private var language = DEFAULT_LANGUAGE; private var otherProperties: MutableMap<Any?, Any?> = HashMap(); private var rights: MutableList<String?> = ArrayList(); private var titles: MutableList<String?> = ArrayList(); private var identifiers: MutableList<Identifier> = arrayListOf(Identifier()); private var subjects: MutableList<String?> = ArrayList(); private var format: String? = MediaTypes.EPUB.getName(); private var types: MutableList<String?> = ArrayList(); private var descriptions: MutableList<String?> = ArrayList(); private var publishers: MutableList<String?> = ArrayList(); private var metaAttributes: MutableMap<String?, String?> = HashMap()
    fun isAutoGeneratedId() = autoGeneratedId; fun getOtherProperties() = otherProperties; fun setOtherProperties(value: MutableMap<Any?, Any?>) { otherProperties = value }
    fun addDate(value: Date): Date { dates.add(value); return value }; fun getDates() = dates; fun setDates(value: MutableList<Date>) { dates = value }
    fun addAuthor(value: Author): Author { authors.add(value); return value }; fun getAuthors() = authors; fun setAuthors(value: MutableList<Author>) { authors = value }
    fun addContributor(value: Author): Author { contributors.add(value); return value }; fun getContributors() = contributors; fun setContributors(value: MutableList<Author>) { contributors = value }
    fun getLanguage() = language; fun setLanguage(value: String) { language = value }; fun getSubjects() = subjects; fun setSubjects(value: MutableList<String?>) { subjects = value }; fun setRights(value: MutableList<String?>) { rights = value }; fun getRights() = rights
    fun getFirstTitle(): String = titles.firstOrNull { StringUtil.isNotBlank(it) } ?: ""; fun addTitle(value: String?): String? { titles.add(value); return value }; fun setTitles(value: MutableList<String?>) { titles = value }; fun getTitles() = titles
    fun addPublisher(value: String?): String? { publishers.add(value); return value }; fun setPublishers(value: MutableList<String?>) { publishers = value }; fun getPublishers() = publishers
    fun addDescription(value: String?): String? { descriptions.add(value); return value }; fun setDescriptions(value: MutableList<String?>) { descriptions = value }; fun getDescriptions() = descriptions
    fun addIdentifier(value: Identifier): Identifier { if (autoGeneratedId && identifiers.isNotEmpty()) identifiers[0] = value else identifiers.add(value); autoGeneratedId = false; return value }; fun setIdentifiers(value: MutableList<Identifier>) { identifiers = value; autoGeneratedId = false }; fun getIdentifiers() = identifiers
    fun setFormat(value: String?) { format = value }; fun getFormat() = format; fun addType(value: String?): String? { types.add(value); return value }; fun getTypes() = types; fun setTypes(value: MutableList<String?>) { types = value }; fun getMetaAttribute(name: String?) = metaAttributes[name]; fun setMetaAttributes(value: MutableMap<String?, String?>) { metaAttributes = value }
    companion object { private const val serialVersionUID = -2437262888962149444L; const val DEFAULT_LANGUAGE = "en" }
}
